apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: nkeycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.3.2
        args: ["start"]
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: 'KC_CACHE_STACK'
          value: 'kubernetes'
        #readinessProbe:
          #httpGet:
            #path: /realms/master
            #port: 8080
          #initialDelaySeconds: 30
          #periodSeconds: 10
          #failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
            periodSeconds: 10
            failureThreshold: 3  
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"