apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: nkeycloak-prd
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
  selector:
    app: keycloak